name: Python check download data

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Check fetch data
      run: python ./download_regions.py
    - name: install flake8
      run: pip install flake8
    - name: Check lint
      run: flake8
